[package]
name = "advent22"
version = "0.0.0"
edition = "2021"

[dependencies]
either = "1.8.0"
itertools = "0.10.5"
paste = "1.0.9"
rayon = "1.6.1"

[dev-dependencies]
indoc = "1.0.7"
test-case = "2.2.2"
